### ISSUE TITLE
Migrate to mariaDB Connector/J driver

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#228]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188012775)

    See for example the teams pom.xml and spring datasource:\
\`\`\`\
datasource:\
    driver-class-name: org.mariadb.jdbc.Driver\
    url: jdbc:mariadb://\{\{ teams.db_host \}\}/\{\{ teams.db_name \}\}\?socketTimeout=30000\
\`\`\`

**Comment by oharsta** [comment]
`
[root@docker1:|TEST2|/opt/openconext/invite]# cat serverapplication.yml | grep -i 'maria'
        dialect: org.hibernate.dialect.MariaDBDialect
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://145.100.191.123/invite?autoReconnect=true
`

**Comment by phavekes** [comment]
Let op: Dit vraagt aanpassingen in het `application.yaml` deploy template
