### ISSUE TITLE
Make email invite message smaller and rename to 'personal note'

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#231]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187741411)

    See figma design in comment

**Comment by MarliesRikken** [comment]
Personal note box mag nog kleiner:

![image](https://github.com/user-attachments/assets/f1588ad3-c4fb-45a1-8f29-075c001383e6)

**Comment by MarliesRikken** [comment]
Still looks bigger than design to me - am I missing something?

**Comment by oharsta** [comment]
It was not deployed yet on the test2 environment. It is now.
