### ISSUE TITLE
Refactor Invitation history as per design

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#233]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187741432)

    	Biggest change:\
- split history in two lists. Accepted \& Pending\
- change columns as shown in figma \(see image\)\
- new buttons to resend/revoke\
- expired status

**Comment by MarliesRikken** [comment]
@oharsta resend & revoke is not yet visible in the 'Pending invitations' tab as far as I can see.

**Comment by oharsta** [comment]
@MarliesRikken We don't have enough space for the two full-size buttons in the rows. We could do what SRAM does, and show icons instead of buttons when hovering the rows. It might be a good idea, to follow the design of SRAM for uniformity anyway?

**Comment by MarliesRikken** [comment]
Laten we daar komende dinsdag even naar kijken - ik ken dat ontwerp niet precies. Maar gelijktrekken klinkt slim, met oog op de toekomst.

**Comment by oharsta** [comment]
Like in SRAM, we show icons when hovering a row. Inspired by google mail and designed last year by Edwin. 

 ![Image](https://github.com/user-attachments/assets/a1de5097-e4e8-46e9-9830-37da649d8cfa)
