### ISSUE TITLE
Change edit end-date in 'users with this role' to match design

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#238]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187741334)

    	- add pencil\
- change date picker \
- update date formatting\
See images

**Comment by MarliesRikken** [comment]
I'm trying to think back to why we went this way. I believe because we also got feedback that some 'standard options' were wanted, but what the standard durations of a for example a semester is might be very different per institution, so it's not really for us to define.

**Comment by MarliesRikken** [comment]
Date picker ziet er OK uit zo.

De remove (uit de gelinkte [pivotal ticket](https://www.pivotaltracker.com/story/show/187741334)) is echter niet zoals design. Staat nu kruisje & potloodje ipv remove blokje, maar remove is ook mogelijk door selectie (voor bluk remove):
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/6b1e7c42-f1dc-4152-ab1d-1ff3af516732">

Voor nu: deze 'bewerken/verwijderen' icons graag aan het eind van de tabel zetten (dus na date accepted).
