### ISSUE TITLE
Expose Invite API for SP Dashboard

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#239]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/188011738)

    SP Dashboard API user needs to create / update / delete Role, invite admins and maintain members. See the tasks for all functionality\
\

- [x] New Remote API user sp_dashboard
- [x] New Scope for sp_dashboard
- [x] New Controller with Basic Auth sp_dashboard secured with the new scope, and reusable for other internal apps
- [x] Expand the RemoteUser with applications that they can access (manage_id, manage_type)
- [x] InternalInvite API: Create Role
- [x] InternalInvite API: New Invite

**Comment by oharsta** [comment]
https://invite.test2.surfconext.nl/ui/swagger-ui/index.html#/internal-invite-controller
