### ISSUE TITLE
API call to get invite url

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#241]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187963610)

    don\\'t send email, but return an invitation-redeem url

Create an API endpoint that creates an invite without sending the email. In the response, the url that would have been in the email is returned. This allows institutions to generate use their own email templates and incorporate the invite flow in their own processes.

**Comment by oharsta** [comment]
@phavekes Would it be sufficient to add an attribute `sendInvitations` to the request body of https://invite.test.surfconext.nl/ui/swagger-ui/index.html#/invitation-controller/newInvitation endpoint wether to send emails or not. If not, then the URL's are returned, else the flow is as it is now.

**Comment by oharsta** [comment]
![Image](https://github.com/user-attachments/assets/4ad156e5-9176-49c6-b4a7-4d214927b925)

**Comment by phavekes** [comment]
@oharsta It's better to always return the redeem-url, also if `sendInvitations` is false or unset
