### ISSUE TITLE
Load userlist paginated

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#242]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187956014)

    For a role with 3000+ users, the full list of users is fetched, but only a part of the list is shown. In the screenshot, the list is 3,5Mb, loaded in 3 seconds, but only 20 users are shown on the screen. Larger roles might take too long to load, or crash a browser.\
\
We should add pagination to the API requests, loading only the first 100 \(\?\) results, and fetch the next page when needed.

Write custom query with optimised search. Something like
```
    SELECT c.id, c.name, c.uuid4, c.expiry_date, c.last_activity_date,
    (SELECT GROUP_CONCAT(DISTINCT u.name) FROM units u
    INNER JOIN collaboration_units cou ON cou.unit_id = u.id
    WHERE cou.collaboration_id = c.id) AS names,
    (SELECT GROUP_CONCAT(DISTINCT t.tag_value) FROM tags t
    INNER JOIN collaboration_tags ct ON ct.tag_id = t.id WHERE ct.collaboration_id = c.id) AS tag_values,
    (SELECT COUNT(id) FROM collaboration_memberships cm WHERE cm.collaboration_id = c.id) AS member_count,
    org.name FROM collaborations c INNER JOIN organisations org ON org.id = c.organisation_id

```

**Comment by MarliesRikken** [comment]
We will not add pagination. 
If more than X users or roles, use search.
If smaller than X users, display in list.

**Comment by phavekes** [comment]
https://github.com/OpenConext/OpenConext-Invite/issues/321

**Comment by MarliesRikken** [comment]
Looks good to me 👍
