### ISSUE TITLE
Niet naam van uitnodiger tonen

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#243]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187934285)

 Wens geuit door TU Delft:

Graag zouden we in de uitnodigingsmail boven het persoonlijke bericht de naam van de uitnodiger willen weglaten, of vervangen met thuiswerken@tudelft.nl. Kan dat?

Dus de uitnodigingen zijn niet afkomstig van een individu maar van een bepaalde rol/functioneel adres.

**Comment by MarliesRikken** [comment]
Per rol instelbaar maken wel naam (of bijv. afdeling) getoond wordt.
Kleine wijziging.

**Comment by MarliesRikken** [comment]
Works in email - but in the login page the name is still displayed. Images from the same role:

![Image](https://github.com/user-attachments/assets/24bc022e-e979-43d1-a92f-fb67d3f288bb)

![Image](https://github.com/user-attachments/assets/52e3528b-f312-4fcd-9d99-6ad642df74a8)

**Comment by MarliesRikken** [comment]
Also change the inviter name in the notification on the login page in _welcome_

**Comment by MarliesRikken** [comment]
@oharsta I still see the inviter name (admin doe) in welcome on login page.

**Comment by oharsta** [comment]
This was not deployed yet, but it is now. 

![Image](https://github.com/user-attachments/assets/b6ba9671-bdde-446e-8ae7-eaf62452c389)
![Image](https://github.com/user-attachments/assets/b4aed022-6eaa-4823-b7b0-ed7df473638b)
