### ISSUE TITLE
Add application manager

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#250]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187689335)

    	We want to split role managers and application managers to give more options to those responsible for an application. And differentiate those from regular role managers. This leads to the following requirements:\
\
Application managers\
+ Manager of an application should only be manager of application.\
\
+ Application manager \'role\' can not have managers, inviters or guests but is = admin role. \(assigned in a similar way to institution admin\). \
+ Enable application owner to make roles for their application. \
+ App manager sees roles that give access to the application\
+ App manager can make roles, invite role managers and inviters.\
\
Role Managers\
- Manager of a role should only be role manager of a role, not of applications.\
\
- Current managers will be renamed to \'role manager\'\
- Role manager can only see the roles they are responsible for. Not other roles that give access to applications.\
\
Effect on Multi-app roles\
- Multi-app role can only be made by Institution Manager.\
Institution manager assigns role manager to multi-app role.\
- App manager cannot edit a multi app - rol. Needs to go to institution manager or role manager if they want changes.\
\

**Comment by MarliesRikken** [comment]
Voorlopig niet - eerst gebruik met huidige autority-structuur
