### ISSUE TITLE
Clean up terms (guest/user) in text 

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#253]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187552912)

    Where \'guest\' or \'gast\' or \'gastgebruiker\' is mentioned - replace with \'gebruiker\' \(NL\) or \'user\' \(ENG\)

**Comment by phavekes** [comment]
@MarliesRikken check of dit klopt

**Comment by MarliesRikken** [comment]
Klopte niet - aangepast in locale.
