### ISSUE TITLE
migrate (v)mbo caretakers to eduID through SURFconext Invite (API)

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#254]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187551618)

    \(V\)MBO institutions are required to onboard student caretakers in their applications/databases, as long as the student is under the age of 18.\
In order to facilitate the use of eduID for those caretakers, the institutions would like to use the SURFconext Invite API to initiate the access to one or more applications using eduID, sending their institutional unique identifier to link the eduID and Invite to the proper institution Identity/Account\(s\).\
\
This feature is to enable the "migration" of exisiting caretaker Identities/Accounts to eduID. Separate features will be drafted to handle onboarding of new caretaker registrations and optimize the eduID onboarding experience.\

**Comment by MarliesRikken** [comment]
Wait till use case is urgent
