### ISSUE TITLE
Add option to create templates for the invite messages

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#256]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187505331)

    Comment Hanze:\
We zouden het erg op prijs stellen als er een template-tekst in het Bericht-veld van de uitnodigingspagina wordt opgenomen. Dit scheelt de medewerkers veel tijd. Hierin kunnen we wat standaard-teksten opnemen.

**Comment by MarliesRikken** [comment]
Optie: set default message on role creation

Opinion: invite should be clear enough that message is redundant
