### ISSUE TITLE
Inform end user if account creation takes some time

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#261]
[This issue is imported from pivotal](https://www.pivotaltracker.com/story/show/187490288)

    	Not all provisioning can be real time. \
- Add a \`user-wait-time\` option to the provisoinings \(default 0 minutes\).\
- Inform the user on welcome it wil take N minutes to activate his account \(if \>0\)\
- register the time the provisioning message was send\
- disable the button to proceed to the application until the wait time expires

**Comment by phavekes** [comment]
Voor nu: Per provisioning instellen of deze real time is

**Comment by oharsta** [comment]
![Image](https://github.com/user-attachments/assets/35376220-cb3a-4217-b542-7fa2ba04d8ec)
