### ISSUE TITLE
Deteling a user when SCIM endpoint is down 

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#293]
When the SCIM endpoint gives an (http) error, the UI does nog respond to that, The delete dialog does not disappear.

We should show an error mentioning the application could not delete the user.

![image](https://github.com/user-attachments/assets/7ea87876-334a-4876-a245-e8956750b61a)

**Comment by oharsta** [comment]
![Image](https://github.com/user-attachments/assets/59759ac3-043a-498c-9e9b-b909a33fb30d)
