### ISSUE TITLE
Show roles in welcome in deterministic order

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-Invite#296]
Log into welcome. Note order of listed roles. Reload page. Roles are in different order. Determine by what criterion roles should be ordered and apply this.

**Comment by oharsta** [comment]
Current implementation is to sort the list of applications based on the application name (with Organisation name) as in Manage, with sub-sorting on the name of the role. See https://github.com/OpenConext/OpenConext-Invite/blob/main/welcome/src/utils/Manage.js#L34
