### ISSUE TITLE
Landing page confusion between roles of the same app

### ISSUE THREAD

**Issue by thijskh** [OpenConext/OpenConext-Invite#297]
In welcome, if you have several different roles with different language pages, but the roles are all tied to the same application.

Example: `urn:collab:person:example.com:thijs` on test2 (log in with Mujina username `thijs`). There are two roles "Thijs test wiki 2" (landing page loeki.tv) and "Thijs test wiki 1" (landing page google.com/ditis1). On welcome, press the button behind Thijs test wiki 1, and be sent to either loeki.tv or google.com/ditis1 (seems random). After reload it's the other way around. Etc.

**Comment by oharsta** [comment]
https://github.com/OpenConext/OpenConext-Invite/commit/75cad5a306cf0abd097b422fc963d651ae6b44e6
