### ISSUE TITLE
Institution admins see too much info

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#312]
An institution admin now sees all roles for applications connected to their IdP.
This also causes them to heve access t all members of these roles. That's to much information.

We could add the institution_guid of the creator to the role when the role is created, and use that to filter the institution-admin's view, but how do we add that to existing roles? And what to do with roles created by the super-admins?

![image](https://github.com/user-attachments/assets/0eabaa30-2184-4ccf-803c-1307a9e8489b)

**Comment by oharsta** [comment]
Currently in production there are only a few roles with more then one application. We could migrate existing roles by querying manage too lookup the `coin:institution_guid` of the SP / RP connected to the role. For non institutional admins we could release the CRM identifier (e.g. the coin:institution_guid of the IdP) in the ARP to Invite and provision it with the super_user.

**Comment by MarliesRikken** [comment]
Reading the suggested solution: it sounds like this is a quick-fix way of introducing a variant of the Institution concept. Since the current situation is causing data-leak we should fix asap and that sounds OK to me.  

I would like to understand the implications a bit better and discuss a proper way to introduce the 'institution' concept for the longer term.

**Comment by oharsta** [comment]
Discussed with Thijs and better is to add an organisation_guid to each Role and populate this with the organisation_guid of the institution_admin. In case of  super_supers we can leave this field blank. In filtering on roles for CRUD we can use the organisation_guid of  the  institution_admin to only show the ones belonging to the user's organisation. @phavekes We need to migrate existing roles, and on production this is probably best to do by hand.

**Comment by phavekes** [comment]
Discussed with Okke:

- Add the institution_guid of the creator to the role one creation
- Add a feature toggle to filter roles to display only roles with the same institution_guid to institution admins
- Add the institution_guid (editable) and the creator (read only) to the role ui for super users
- If the institution_guid of a role is null, and the filter feature toggle is on, only the super-admin can see the role

This way, we can manually fill the institution_guids for existing roles, and later hide the roles from institution admins.
