### ISSUE TITLE
Pagination and limitations

### ISSUE THREAD

**Issue by oharsta** [OpenConext/OpenConext-Invite#321]
In https://github.com/OpenConext/OpenConext-Invite/issues/242 the issue is raised that loading all database content does not scale. The generic solution is to search server-side with server-side pagination and default sort on the newest entries. 

However in the case of invite this poses a problem with regard to the applications, which reside in Manage. We can't search on those server side without syncing all data between Manage and Invite (which we don't want to avoid stale data / cache problems). The drop-down with all applications can also only be created when all data is loaded and this functionality is not possible anymore when we paginate server-side. 

We need a GUI way to show that searching is only related to name, description of the role and other data we show is not searchable. Maybe we can use the placeholder (like github does), and / or move the application column in de role overview to a less prominent place.

**Comment by oharsta** [comment]
<img width="1815" alt="image" src="https://github.com/user-attachments/assets/03143471-93e1-4b12-b18b-444f409d5fb2">

**Comment by phavekes** [comment]
Will be solved in https://github.com/OpenConext/OpenConext-Invite/issues/242
