### ISSUE TITLE
List of apps per role is linked to URL of one app

### ISSUE THREAD

**Issue by oharsta** [OpenConext/OpenConext-Invite#327]
Given a role that has multiple applications. These applications are listed in the role detail screen. However all the apps listed have one single hyperlink around them which links to the url of one of the applications. It would make more sense to give each of the names its own link.

In the screenshot below the entire line next to the i-globe links to https://wiki.surfnet.nl
![Schermafbeedling](https://github.com/user-attachments/assets/0a67253b-719c-480e-84a6-a2ca8d3b74a7)

**Comment by MarliesRikken** [comment]
Tested - works as intended now
